export enum NotificationTypeEnum {
  INFO = 'INFO',
  DANGEROUS = 'DANGEROUS',
  ALERT = 'ALERT',
  WARNING = 'WARNING',
  ORDER_STATUS_CHANGED = 'ORDER_STATUS_CHANGED',
  MODERATION_REJECTED = 'MODERATION_REJECTED',
  MODERATION_APPROVED = 'MODERATION_APPROVED',
}
